language: php
php:
  - 7.2
  - 7.3

before_script:
  - composer require php-coveralls/php-coveralls
  - composer install --dev --prefer-source

script:
  - composer test

after_script:
  - php vendor/bin/coveralls -v
